version: '3.8'

volumes:
  admin_backend_postgresdata:
  respondent_backend_postgresdata:
  minio_data:
  clickhouse_data:

services:
  admin_backend_postgres:
    image: postgres
    env_file: './packages/admin-backend/.env'
    volumes:
      - admin_backend_postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  respondent_backend_postgres:
    image: postgres
    env_file: './packages/respondent-backend/.env'
    volumes:
      - respondent_backend_postgresdata:/var/lib/postgresql/data
    ports:
      - 5433:5433
    command: -p 5433
  minio:
    image: minio/minio
    env_file: './packages/admin-backend/.env'
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
  clickhouse:
    image: yandex/clickhouse-server:latest
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    env_file: './packages/event-collector/.env'
    ports:
      - 8123:8123
