FROM node:20-alpine AS base
RUN npm install -g pnpm@8.8.0 prisma tsx

FROM base AS build
WORKDIR /usr/src/app
COPY . ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile &&\
  pnpm --filter 'event-collector' build &&\
  pnpm deploy --filter='event-collector' --prod /backend

FROM build AS backend
COPY --from=build /backend /backend
WORKDIR /backend
CMD pnpm db:migrate:deploy && node dist/main.js
EXPOSE ${APP_PORT}